import AppKit
import Combine

/// Memantau clipboard dengan polling `changeCount` (cara yang diizinkan App
/// Store — TANPA Accessibility / Input Monitoring). Menghormati flag privasi
/// dari pengelola kata sandi (Transient / Concealed / Autogenerated).
final class ClipboardMonitor: ObservableObject {
    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount
    var onNewItem: ((ClipItem) -> Void)?
    var isPaused = false

    func start() {
        lastChange = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Tandai perubahan yang kita picu sendiri (saat menyalin ulang) supaya
    /// tidak terekam dua kali.
    func acknowledgeOwnChange() {
        lastChange = NSPasteboard.general.changeCount
    }

    private func poll() {
        guard !isPaused else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount

        let types = pb.types ?? []
        // Hormati item yang ditandai privat (mis. dari 1Password).
        let privacyFlags: [NSPasteboard.PasteboardType] = [
            .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.ConcealedType"),
            .init("org.nspasteboard.AutoGeneratedType"),
        ]
        if privacyFlags.contains(where: { types.contains($0) }) { return }

        if let str = pb.string(forType: .string),
           !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            onNewItem?(ClipItem(kind: .text, text: str))
            return
        }
        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           let img = NSImage(data: data),
           let png = img.pngData() {
            onNewItem?(ClipItem(kind: .image, text: "Image", imageData: png))
        }
    }
}

extension NSImage {
    func pngData() -> Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
